const products = [

  // ── TEMU PICKS ───────────────────────────────────────────────────────

  {
    id: 'aero-socks',
    name: 'Aero Socks',
    cat: 'Cycling',
    filters: ['cycling', 'under5'],
    branded: 30,
    price: 3.89,
    save: 26,
    stars: 4.8,
    reviews: 1269,
    link: 'aero-socks.html',
    tagline: 'Same feel as $30 Castelli aero socks — buy five for less than one branded pair.',
    isArticle: true,
    newUser: true,
  },
  {
    id: 'base-layer',
    name: 'Base Layer Vest',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 48,
    price: 8,
    save: 40,
    stars: 4.8,
    reviews: 1141,
    link: 'https://temu.to/k/e6lo7odn6et',
    tagline: 'Same quick-dry mesh as $48 Castelli or Craft — the unsung hero of your kit.',
  },
  {
    id: 'cycling-cap',
    name: 'Cycling Cap',
    cat: 'Cycling',
    filters: ['cycling', 'under5'],
    branded: 24,
    price: 4,
    save: 20,
    stars: 4.8,
    reviews: 293,
    link: '#',
    tagline: 'Feels and looks like a $24 Castelli cap. One rider has bought it five times.',
  },
  {
    id: 'tyre-levers',
    name: 'Tyre Levers',
    cat: 'Tools',
    filters: ['tools', 'under5'],
    branded: 10,
    price: 2,
    save: 8,
    stars: 4.9,
    reviews: 69,
    link: 'https://temu.to/k/e5keep9hknb',
    tagline: 'POM engineering plastic — same as Park Tool levers. Two for $2. Throw them everywhere.',
  },
  {
    id: 'soft-flask',
    name: 'Collapsible Soft Flask',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 20,
    price: 4,
    save: 15,
    stars: 4.8,
    reviews: 7979,
    link: 'https://temu.to/k/ehbhw6zee11',
    tagline: 'Fits any vest pocket and collapses when empty — same as Salomon for 1/5 the price.',
  },
  {
    id: 'multi-tool',
    name: '11-in-1 Multi-Tool',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 35,
    price: 6,
    save: 29,
    stars: 4.7,
    reviews: 4142,
    link: 'https://temu.to/k/ep7w4rl0n28',
    tagline: '11 tools in a jersey pocket. Hex keys, chain breaker, spoke wrench. $29 less than Lezyne.',
  },
  {
    id: 'tpu-tube',
    name: 'TPU Inner Tube 700C',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 40,
    price: 4,
    save: 36,
    stars: 4.8,
    reviews: 327,
    link: 'https://temu.to/k/ea2dkjc8mdc',
    tagline: '36g vs 110g butyl. Real rolling gains. One rider: zero punctures at 12,000km.',
  },
  {
    id: 'saddle-bag',
    name: 'Saddle Bag',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 35,
    price: 9,
    save: 25,
    stars: 4.9,
    reviews: 603,
    link: 'https://temu.to/k/eta1sitshpa',
    tagline: 'Highest-rated pick at 4.9★. Holds tubes, levers, multi-tool, phone. Zero bounce.',
  },
  {
    id: 'bottle-cage',
    name: 'Carbon-Look Bottle Cage',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 55,
    price: 3,
    save: 52,
    stars: 4.7,
    reviews: 315,
    link: 'https://temu.to/k/erwsx59ylps',
    tagline: 'ABS carbon-look cage. Holds secure, looks sharp. $52 less than Elite or Arundel carbon.',
  },
  {
    id: 'rear-light',
    name: 'Rear Light with Brake Sensor',
    cat: 'Safety',
    filters: ['safety', 'bigsave'],
    branded: 100,
    price: 6,
    save: 88,
    stars: 4.8,
    reviews: 673,
    link: 'https://temu.to/k/enwlc8bz1zg',
    tagline: 'Brake sensor auto-brightens when you slow — like a car brake light. Garmin Varia is $100+.',
  },
  {
    id: 'cycling-gloves-half',
    name: 'Half-Finger Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 45,
    price: 10,
    save: 35,
    stars: 4.9,
    reviews: 257,
    link: 'https://temu.to/k/emg93mxe2p7',
    tagline: 'Anti-slip grip, pull tabs, padded palm — same as $45 Castelli half-finger gloves for $10.',
  },
  {
    id: 'arm-sleeves',
    name: 'UV Arm Sleeves (3-pack)',
    cat: 'Cycling',
    filters: ['cycling', 'running', 'bigsave'],
    branded: 105,
    price: 9,
    save: 96,
    stars: 4.8,
    reviews: 586,
    link: 'https://temu.to/k/e09mo340h37',
    tagline: 'Three pairs for $9 — a single Castelli pair costs $35. Keep one on the bike, one in the run kit.',
  },
  {
    id: 'winter-gloves',
    name: 'Winter Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 60,
    price: 9,
    save: 51,
    stars: 4.8,
    reviews: 452,
    link: 'https://temu.to/k/em2up5dgq7z',
    tagline: 'Windproof fleece-lined with touchscreen tips — tested at 3°C. $51 less than Gore.',
  },
  {
    id: 'summer-gloves',
    name: 'Summer Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 35,
    price: 6,
    save: 29,
    stars: 4.8,
    reviews: 660,
    link: 'https://temu.to/k/ebf1r80mgkf',
    tagline: 'Race-day minimal gloves — same look and feel as Giro or Specialized for $6.',
  },
  {
    id: 'balaclava',
    name: 'Cycling Balaclava',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 40,
    price: 10,
    save: 30,
    stars: 4.8,
    reviews: 122,
    link: 'https://temu.to/k/eltjvwctovt',
    tagline: 'Full head, face, and neck coverage for cold morning rides — $30 less than Castelli.',
  },
  {
    id: 'bar-tape',
    name: 'Handlebar Tape',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 30,
    price: 8,
    save: 22,
    stars: 4.9,
    reviews: 465,
    link: 'https://temu.to/k/egw7b3p3pxq',
    tagline: 'Wraps like Fizik or Lizard Skins. One rider has bought it nine times.',
  },
  {
    id: 'mini-pump-cx',
    name: 'Mini Frame Pump',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 45,
    price: 16,
    save: 29,
    stars: 4.8,
    reviews: 166,
    link: 'https://temu.to/k/esgmzz4hf0c',
    tagline: 'Aluminium alloy to 130 PSI, Presta and Schrader — same as Lezyne for $29 less.',
  },
  {
    id: 'mini-pump-enlee',
    name: 'Ultracompact Mini Pump',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 45,
    price: 14,
    save: 31,
    stars: 4.8,
    reviews: 202,
    link: 'https://temu.to/k/eziomgb8exg',
    tagline: 'Pen-sized — fits inside the saddle bag underneath the spare tube. Zero extra space.',
  },
  {
    id: 'mini-pump-west',
    name: 'Mini Pump (Budget Pick)',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 30,
    price: 9,
    save: 21,
    stars: 4.8,
    reviews: 381,
    link: 'https://temu.to/k/el8omjqk5d5',
    tagline: 'Pumped a full 29" MTB tube from flat in 3–4 minutes. Includes all valve adapters.',
  },
  {
    id: 'repair-kit',
    name: 'Complete Repair Kit',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 70,
    price: 21,
    save: 49,
    stars: 4.8,
    reviews: 566,
    link: 'https://temu.to/k/ebmlb008d88',
    tagline: '17-in-1 tool, tyre levers, and mini pump in a saddle bag — the one-purchase flat kit.',
  },
  {
    id: 'gps-mount',
    name: 'GPS Computer Mount',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 50,
    price: 6,
    save: 44,
    stars: 4.8,
    reviews: 825,
    link: 'https://temu.to/k/eiqc42xlow8',
    tagline: 'Holds solid over cobbles and rough road. $44 less than the official Garmin out-front mount.',
  },
  {
    id: 'stem-mount',
    name: 'Stem Computer Mount',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 45,
    price: 10,
    save: 35,
    stars: 4.8,
    reviews: 113,
    link: 'https://temu.to/k/ebxqyggsmvz',
    tagline: 'Aluminium + carbon GPS stem mount — looks like a €40 K-Edge, costs $10.',
  },
  {
    id: 'cleaning-kit',
    name: 'Bike Cleaning Kit (8-piece)',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 50,
    price: 16,
    save: 34,
    stars: 4.9,
    reviews: 221,
    link: 'https://temu.to/k/em2qbrjkbyt',
    tagline: '8-piece brush set for chain, cassette, and frame — directly compared to Muc-Off by buyers.',
  },
  {
    id: 'running-caps',
    name: 'Running Caps (2-pack)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 60,
    price: 8,
    save: 52,
    stars: 4.8,
    reviews: 514,
    link: 'https://temu.to/k/eo6u0nmxqb2',
    tagline: 'Two mesh running caps for $8 — vs $30 each for Nike or Salomon equivalents.',
  },
  {
    id: 'calf-sleeves',
    name: 'Compression Calf Sleeves',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 50,
    price: 6,
    save: 44,
    stars: 4.8,
    reviews: 4829,
    link: 'https://temu.to/k/ev6b8htdopf',
    tagline: 'Reduces travel swelling and speeds recovery — 72,000+ sold. $44 less than Compressport.',
  },
  {
    id: 'running-belt',
    name: 'Running Belt',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 35,
    price: 8,
    save: 27,
    stars: 4.8,
    reviews: 948,
    link: 'https://temu.to/k/eoq9u2nze0b',
    tagline: 'Zero-bounce belt for phone, keys, and card — 1M+ sold. $27 less than Nathan or Flipbelt.',
  },
  {
    id: 'elastic-laces',
    name: 'Elastic No-Tie Laces',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 12,
    price: 1.7,
    save: 10,
    stars: 4.8,
    reviews: 9201,
    link: 'https://temu.to/k/eexx1xt6su3',
    tagline: 'Shoes on in 3 seconds in T2 — same as $12 Lock Laces for $1.70.',
  },
  {
    id: 'foam-roller',
    name: 'Foam Roller Set (5-piece)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 70,
    price: 14,
    save: 56,
    stars: 4.8,
    reviews: 370,
    link: 'https://temu.to/k/e56n3u6bii7',
    tagline: '5-piece recovery kit — "not worse than Blackroll" per one buyer. $56 less than branded.',
  },
  {
    id: 'resistance-bands',
    name: 'Resistance Bands Set',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 55,
    price: 13,
    save: 42,
    stars: 4.8,
    reviews: 278,
    link: 'https://temu.to/k/eosiemk6lob',
    tagline: 'Up to 6 TPE resistance bands — full strength kit for $42 less than Rogue or Perform Better.',
  },
  {
    id: 'mini-bands',
    name: 'Mini Resistance Bands (3-pack)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 30,
    price: 7,
    save: 23,
    stars: 4.8,
    reviews: 720,
    link: 'https://temu.to/k/equ2h6wy1ac',
    tagline: 'Three mini bands for hip activation and injury prevention. $23 less than physio brands.',
  },
  {
    id: 'race-belt',
    name: 'Triathlon Race Belt',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 18,
    price: 3,
    save: 15,
    stars: 4.8,
    reviews: 1054,
    link: 'https://temu.to/k/e3nurz30cdv',
    tagline: 'Race belt with gel loops — T2 ready in 2 seconds. Holds 6 gels. $3 vs $18 branded.',
  },
  {
    id: 'swim-cap',
    name: 'Silicone Swim Cap',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 15,
    price: 2.5,
    save: 13,
    stars: 4.8,
    reviews: 984,
    link: 'https://temu.to/k/et2k74knz7l',
    tagline: 'Silicone twice as thick as branded equivalents per one buyer — at $2.50, just buy five.',
  },

  // ── ALIEXPRESS PICKS ─────────────────────────────────────────────────

  {
    id: 'cycling-jersey-ss',
    name: 'Cycling Jersey',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 90,
    price: 10.94,
    save: 79,
    stars: 4.8,
    reviews: 3247,
    link: 'https://s.click.aliexpress.com/e/_EHc1YVg',
    tagline: 'Same race-day look as a $90 Castelli jersey. Costs $11.',
    source: 'aliexpress',
  },
  {
    id: 'overshoes',
    name: 'Cycling Overshoes',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 60,
    price: 13.85,
    save: 46,
    stars: 4.7,
    reviews: 1584,
    link: 'https://s.click.aliexpress.com/e/_EvQd24W',
    tagline: 'Waterproof neoprene shoe covers — stays dry for $14 vs $60 branded.',
    source: 'aliexpress',
  },
  {
    id: 'hydration-vest',
    name: 'Running Hydration Vest',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 100,
    price: 6.05,
    save: 94,
    stars: 4.8,
    reviews: 5921,
    link: 'https://s.click.aliexpress.com/e/_ExFvLp8',
    tagline: 'Feels like a Salomon vest. Costs $94 less.',
    source: 'aliexpress',
  },
  {
    id: 'bib-shorts',
    name: 'Bib Shorts',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 140,
    price: 24.41,
    save: 116,
    stars: 4.9,
    reviews: 4813,
    link: 'https://s.click.aliexpress.com/e/_EQd5V0a',
    tagline: '6-hour padded bibs — Castelli-level comfort for $116 less.',
    source: 'aliexpress',
  },
  {
    id: 'cycling-sunglasses',
    name: 'Cycling Sunglasses',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 180,
    price: 4.30,
    save: 176,
    stars: 4.7,
    reviews: 2436,
    link: 'https://s.click.aliexpress.com/e/_EJyXqp0',
    tagline: 'UV400 lenses, aero frame. Looks like Oakley. Costs $4.',
    source: 'aliexpress',
  },
  {
    id: 'jersey-ls',
    name: 'Long Sleeve Jersey',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 110,
    price: 25.30,
    save: 85,
    stars: 4.8,
    reviews: 3092,
    link: 'https://s.click.aliexpress.com/e/_EIH3daI',
    tagline: 'SPF50+ race jersey — premium fit and feel for $85 less.',
    source: 'aliexpress',
  },
  {
    id: 'cycling-gilet',
    name: 'Cycling Wind Gilet',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 100,
    price: 12.55,
    save: 87,
    stars: 4.8,
    reviews: 1927,
    link: 'https://s.click.aliexpress.com/e/_EwvKNfY',
    tagline: 'Windproof jersey-pocket gilet — $87 cheaper than Castelli Perfetto.',
    source: 'aliexpress',
  },
  {
    id: 'tt-handlebar',
    name: 'Carbon TT Handlebar',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 250,
    price: 36.91,
    save: 213,
    stars: 4.7,
    reviews: 1183,
    link: 'https://s.click.aliexpress.com/e/_Ewg1SX8',
    tagline: '3K matte carbon TT bars — same aero position as Zipp for $213 less.',
    source: 'aliexpress',
  },
  {
    id: '3d-saddle',
    name: '3D Printed Bike Saddle',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 400,
    price: 43.02,
    save: 357,
    stars: 4.9,
    reviews: 2674,
    link: 'https://s.click.aliexpress.com/e/_ExdfFQI',
    tagline: '3D-printed ultralight saddle — same tech as $400 Specialized Power Mirror.',
    source: 'aliexpress',
  },
  {
    id: 'aero-bars',
    name: 'Clip-On Aero Bars',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 90,
    price: 14.82,
    save: 75,
    stars: 4.8,
    reviews: 6341,
    link: 'https://s.click.aliexpress.com/e/_EGHCLAO',
    tagline: 'Adds a full TT position to any road bike for $14.',
    source: 'aliexpress',
  },
];
