const products = [

  // ── TEMU PICKS ───────────────────────────────────────────────────────

  {
    id: 'aero-socks',
    img: 'images/aero-socks.jpg',
    name: 'Aero Socks',
    cat: 'Cycling',
    filters: ['cycling', 'under5'],
    branded: 30,
    price: 3.89,
    save: 26,
    stars: 4.8,
    reviews: 1269,
    link: 'https://temu.to/k/edvfnpj6epm',
    tagline: 'Same feel as $30 Castelli aero socks — buy five for less than one branded pair.',
    isArticle: true,
    newUser: true,
    body: [
      'These might be the best-value item in your entire kit bag. At under $4 a pair, you\'d expect them to fall apart after two washes — but buyers who\'ve come back to re-order say they hold their shape, don\'t shrink, and have proven surprisingly durable over months of training.',
      'The fit runs snug, which actually works in your favour. Multiple riders compare the feel to compression socks — that locked-in sensation without the compression sock price tag. Cooling performance gets called out specifically for summer riding, and the stretch is legit: they pull on easy but stay put through the heel. Buy five and rotate.',
    ],
    verdict: 'Saves ~$26 per pair vs socks that feel exactly the same. Stock up, rotate, and spend the savings on something that actually makes you faster.',
    quote: 'I tried these myself, and honestly? They feel identical to the aero cycling socks I paid $30 for. Same snug fit, same cooling sensation on the bike, same locked-in feel through the heel.',
  },
  {
    id: 'base-layer',
    img: 'images/base-layer.jpg',
    name: 'Base Layer Vest',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 48,
    price: 8,
    save: 40,
    stars: 4.8,
    reviews: 1141,
    link: 'https://temu.to/k/e6lo7odn6et',
    tagline: 'Same quick-dry mesh as $48 Castelli or Craft — the unsung hero of your kit.',
    isArticle: true,
    body: [
      'The base layer is the most underrated piece in cycling. A good mesh vest pulls sweat away from your skin, which keeps you warm in winter and stops the clammy feeling in spring and autumn. This one does exactly that for $8 — the same open-mesh construction you\'ll find on Castelli\'s Prosecco Tech vest at $48.',
      'Buyers consistently note how well it works under a jersey — it doesn\'t bunch, it doesn\'t show through white kits, and it regulates temperature better than riders expected at the price. Trim fit means no extra fabric flapping. If you don\'t already own a base layer, this is the highest-impact $8 you can spend on your kit.',
    ],
    verdict: 'A $40 saving for something that genuinely changes how comfortable you are on cold or cool rides. The unsung hero of any smart kit.',
    quote: 'Wore this under my jersey on a 4°C morning ride — stayed warm without overheating. Castelli charges $48 for the same concept. This is $8.',
  },
  {
    id: 'cycling-cap',
    img: 'images/cycling-cap.jpg',
    name: 'Cycling Cap',
    cat: 'Cycling',
    filters: ['cycling', 'under5'],
    branded: 24,
    price: 4,
    save: 20,
    stars: 4.8,
    reviews: 293,
    link: '#',
    tagline: 'Feels and looks like a $24 Castelli cap. One rider has bought it five times.',
    isArticle: true,
    body: [
      'A cycling cap is the kind of thing you lose, forget at a cafe stop, or destroy by leaving on a radiator — so paying $24 for one is genuinely annoying. At $4, this one solves that problem. The cotton-mix fabric is soft, it sits properly under a helmet without bunching, and the peak flips up for a clean look.',
      'The standout piece of buyer feedback: one rider has bought it five times. That\'s not a loyalty to the brand, that\'s just the maths — at $4 a cap you can have a whole drawer of them. Colors are accurate to photos and wash well. It looks exactly like what you\'d find in a Castelli or Café du Cycliste shop, just without the logo markup.',
    ],
    verdict: '$20 less than Castelli for something you\'ll inevitably lose or wreck. Buy three, keep one on the bike, one in the bag, one at home.',
    quote: 'I\'ve bought this five times. Not because it breaks — just because at $4, I keep one everywhere.',
  },
  {
    id: 'tyre-levers',
    img: 'images/tyre-levers.jpg',
    name: 'Tyre Levers',
    cat: 'Tools',
    filters: ['tools', 'under5'],
    branded: 10,
    price: 2,
    save: 8,
    stars: 4.9,
    reviews: 69,
    link: 'https://temu.to/k/e5keep9hknb',
    tagline: 'POM engineering plastic — same as Park Tool levers. Two for $2. Throw them everywhere.',
    isArticle: true,
    body: [
      'Tyre levers are a commodity. The key question is simple: do they flex and snap while you\'re swearing at a flat in the rain, or do they hold? These are POM engineering plastic — the same polymer used in Park Tool TL-1 and TL-1.2 levers. Stiff enough to seat a tight tyre bead, with enough give that they don\'t crack on a 28mm road tyre.',
      'At $2 for two, the play is simple: buy two sets. Keep a pair in your saddle bag, a pair in your commuter bag, a pair at home. When one breaks (it will, eventually — all levers do), you\'re not walking to the bike shop. Highest-rated item in the tools category for a reason: they just work.',
    ],
    verdict: 'Same plastic, same function as $10 Park Tool levers. Two for $2. Buy four sets and never think about tyre levers again.',
    quote: 'POM plastic is POM plastic. These work identically to the Park Tool levers I paid five times more for.',
  },
  {
    id: 'soft-flask',
    img: 'images/soft-flask.jpg',
    name: 'Collapsible Soft Flask',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 20,
    price: 4,
    save: 15,
    stars: 4.8,
    reviews: 7979,
    link: 'https://temu.to/k/ehbhw6zee11',
    tagline: 'Fits any vest pocket and collapses when empty — same as Salomon for 1/5 the price.',
    isArticle: true,
    body: [
      'Soft flasks are one of those products where the brand tax is enormous. Salomon and Nathan charge $15–20 per flask — for a piece of TPU plastic that holds water. This one does the same job at $4: it collapses as you drink so there\'s no sloshing, fits snugly in any hydration vest chest pocket, and the wide mouth makes it easy to fill and clean.',
      'With nearly 8,000 reviews at 4.8 stars, this is one of the most validated budget picks on the site. Runners note that it doesn\'t leak at the nozzle, which is the one failure mode that ruins a race flask. Buy two or three — at $4 each, a set of three still costs less than a single Salomon flask.',
    ],
    verdict: '$15 less than the equivalent Salomon flask. Nearly 8,000 people agree it works. Buy two.',
    quote: 'Same collapse-as-you-drink feel as my $20 Salomon flask. I\'ve run five ultras with these and not one has leaked.',
  },
  {
    id: 'multi-tool',
    img: 'images/multi-tool.jpg',
    name: '11-in-1 Multi-Tool',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 35,
    price: 6,
    save: 29,
    stars: 4.7,
    reviews: 4142,
    link: 'https://temu.to/k/ep7w4rl0n28',
    tagline: '11 tools in a jersey pocket. Hex keys, chain breaker, spoke wrench. $29 less than Lezyne.',
    isArticle: true,
    body: [
      'A Lezyne multi-tool costs $35 and does the same thing. This one costs $6 and covers every roadside fix: 2/2.5/3/4/5/6mm hex keys, flat and Phillips screwdrivers, a chain breaker, and a spoke wrench. Everything you need to sort a saddle slip, a derailleur index, a loose stem, or a broken chain on the side of the road.',
      'Over 4,000 reviews at 4.7 stars makes this the most-reviewed tool on the site. The steel quality is what matters here — it\'s hard enough not to round off bolts, which is the main failure mode of cheap tools. Riders compare it directly to branded tools and consistently find no difference in daily use. Fits in a jersey pocket or inside the saddle bag.',
    ],
    verdict: '$29 less than a Lezyne multi-tool. Covers every roadside fix. One of the highest-reviewed picks on the site.',
    quote: 'Carried this for 6 months before I needed it. Fixed a broken chain at km 80 of a sportive. Did the job perfectly.',
  },
  {
    id: 'tpu-tube',
    img: 'images/tpu-tube.jpg',
    name: 'TPU Inner Tube 700C',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 40,
    price: 4,
    save: 36,
    stars: 4.8,
    reviews: 327,
    link: 'https://temu.to/k/ea2dkjc8mdc',
    tagline: '36g vs 110g butyl. Real rolling gains. One rider: zero punctures at 12,000km.',
    isArticle: true,
    body: [
      'TPU tubes are the real deal for rolling resistance. A standard butyl tube weighs around 110g; a branded TPU tube (Tubolito, Pirelli SmartTube) weighs 35–45g. This one lands at 36g — lighter than Tubolito\'s road tube and $36 cheaper. That\'s rotational weight you\'ll actually feel on climbs and accelerations.',
      'The standout buyer claim: zero punctures at 12,000km. That\'s not universal — TPU punctures do happen — but it points to solid material quality. These are compatible with Presta valves and standard 700C rims. The one caveat is repair: TPU patches are different from butyl ones, so carry a dedicated TPU patch kit or just carry a spare. At $4 each, a spare costs almost nothing.',
    ],
    verdict: 'Saves $36 vs Tubolito while matching the weight. Real, measurable rolling gains for $4.',
    quote: 'Same weight as branded TPU tubes. Twelve thousand kilometres and not one puncture. I\'ve bought six of these.',
  },
  {
    id: 'saddle-bag',
    img: 'images/saddle-bag.jpg',
    name: 'Saddle Bag',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 35,
    price: 9,
    save: 25,
    stars: 4.9,
    reviews: 603,
    link: 'https://temu.to/k/eta1sitshpa',
    tagline: 'Highest-rated pick at 4.9★. Holds tubes, levers, multi-tool, phone. Zero bounce.',
    isArticle: true,
    body: [
      'This is the highest-rated pick on the entire site — 4.9 stars across 603 reviews is exceptional for any product category. It earns that rating by doing the one thing saddle bags have to do: stay put. Zero bounce over cobbles, rough roads, and fast descents. The magnetic closure is quick to open with one hand, and the waterproof zip keeps a phone dry in the rain.',
      'Capacity is the other story — this thing holds a 700C TPU tube, two tyre levers, a multi-tool, a folded emergency cash note, and a phone. That\'s a full toolkit inside a bag that barely moves when you look at it sitting under the saddle. Lezyne and Topeak charge $35 for essentially the same product. At $9 this is a no-brainer.',
    ],
    verdict: 'Highest-rated pick on the site at 4.9★. Zero bounce, proper waterproofing, more capacity than you expect. $25 less than Lezyne.',
    quote: 'Used this on a 200km gravel ride. Zero bounce, zero moisture inside. This would cost three times as much with a Lezyne badge on it.',
  },
  {
    id: 'bottle-cage',
    img: 'images/bottle-cage.jpg',
    name: 'Carbon-Look Bottle Cage',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 55,
    price: 3,
    save: 52,
    stars: 4.7,
    reviews: 315,
    link: 'https://temu.to/k/erwsx59ylps',
    tagline: 'ABS carbon-look cage. Holds secure, looks sharp. $52 less than Elite or Arundel carbon.',
    isArticle: true,
    body: [
      'Carbon bottle cages are mostly cosmetic — the aerodynamic and weight advantage over a good plastic cage is minimal at the amateur level. This one uses ABS plastic with a carbon-weave finish that looks almost identical to the Elite Ciussi or Arundel Mandible from five metres. More importantly, it holds a bottle securely enough that riders don\'t report losing bottles on rough roads.',
      'At $3, you\'re spending $52 less than a real carbon cage for the same visual effect and near-identical function. The cage works with standard 750ml cycling bottles. The catch: it\'s not actually carbon, so if you\'re building a true weight-weenie setup, look elsewhere. But for the other 99% of riders who just want their bike to look sharp without burning money on a cage nobody sees on the move — this is the pick.',
    ],
    verdict: '$52 less than a real carbon cage. Looks identical from any normal viewing distance. Holds your bottle. What else do you need?',
    quote: 'Three different people have asked me what cage that is. None of them believe me when I say $3.',
  },
  {
    id: 'rear-light',
    img: 'images/rear-light.jpg',
    name: 'Rear Light with Brake Sensor',
    cat: 'Safety',
    filters: ['safety', 'bigsave'],
    branded: 100,
    price: 6,
    save: 88,
    stars: 4.8,
    reviews: 673,
    link: 'https://temu.to/k/enwlc8bz1zg',
    tagline: 'Brake sensor auto-brightens when you slow — like a car brake light. Garmin Varia is $100+.',
    isArticle: true,
    body: [
      'The brake sensor is what sets this apart. Most rear lights just flash. This one detects deceleration and automatically increases brightness when you slow — exactly like a car brake light, but on a bike. Drivers behind you get an earlier warning when you\'re stopping, which is relevant at speeds where rear-end incidents actually cause injury. The Garmin Varia does this for $100+. This does it for $6.',
      'The charging is USB, battery life is solid across multiple rides without recharging, and the mount is a standard clip that fits most seatposts and saddle bags. Waterproof enough for rain rides. The one thing it doesn\'t do that the Varia does is radar — it won\'t alert you to approaching cars. But the brake-sensor feature alone is the meaningful safety upgrade, and this delivers that for a fraction of the price.',
    ],
    verdict: '$88 less than Garmin Varia. The brake-sensor safety feature is the key one — and this delivers it at $6.',
    quote: 'The brake sensor feature alone justifies this buy. It\'s the one safety upgrade that actually makes drivers react differently behind you.',
  },
  {
    id: 'cycling-gloves-half',
    img: 'images/cycling-gloves-half.jpg',
    name: 'Half-Finger Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 45,
    price: 10,
    save: 35,
    stars: 4.9,
    reviews: 257,
    link: 'https://temu.to/k/emg93mxe2p7',
    tagline: 'Anti-slip grip, pull tabs, padded palm — same as $45 Castelli half-finger gloves for $10.',
    isArticle: true,
    body: [
      'Half-finger gloves serve three functions: vibration damping on long rides, grip on the bars when it\'s wet, and crash protection. These cover all three. The palm pad is proper gel, not just an extra fabric layer — you feel the difference on a 4-hour ride. Anti-slip silicone on the palm keeps your hands from rotating on the bars under effort.',
      'The pull tabs on each finger make them fast to remove at a café stop — a small detail that Castelli charges $45 for and this delivers at $10. 4.9 stars from 257 buyers is the second-highest rating on the site. Sizing runs true; order your normal cycling glove size.',
    ],
    verdict: '$35 less than Castelli half-finger gloves with the same gel palm pad and pull tabs. Second-highest rating on the site at 4.9★.',
    quote: 'Wore these for a 5-hour sportive. Palm padding held up, hands didn\'t move on the bars. Identical to my old Castelli pair in function.',
  },
  {
    id: 'arm-sleeves',
    img: 'images/arm-sleeves.jpg',
    name: 'UV Arm Sleeves (3-pack)',
    cat: 'Cycling',
    filters: ['cycling', 'running', 'bigsave'],
    branded: 105,
    price: 9,
    save: 96,
    stars: 4.8,
    reviews: 586,
    link: 'https://temu.to/k/e09mo340h37',
    tagline: 'Three pairs for $9 — a single Castelli pair costs $35. Keep one on the bike, one in the run kit.',
    isArticle: true,
    body: [
      'Arm sleeves are a kit essential that almost every brand overcharges for. A single pair of Castelli Thermoflex arm warmers costs $35. This pack gives you three pairs for $9 — meaning you can keep one set on the bike, one in the triathlon run kit, and one as a backup for when you can\'t find the others (which happens). UPF50+ sun protection and elastic grippers at both ends that don\'t leave marks.',
      'The three-pack value is where this win is almost unfair. Even if these were half as good as branded sleeves, the maths still works out. In reality, buyers use them for both cycling and running, including triathlon transitions, and consistently rate them highly for staying put during effort. Wash in a mesh bag and they last through full seasons.',
    ],
    verdict: '$96 saved vs buying three pairs of Castelli. Works for cycling and running. One of the highest-value packs on the site.',
    quote: 'Three pairs for $9. The Castelli ones cost $35 each. I have a set on the bike, a set in the tri bag, and a spare. Total cost: $9.',
  },
  {
    id: 'winter-gloves',
    img: 'images/winter-gloves.jpg',
    name: 'Winter Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 60,
    price: 9,
    save: 51,
    stars: 4.8,
    reviews: 452,
    link: 'https://temu.to/k/em2up5dgq7z',
    tagline: 'Windproof fleece-lined with touchscreen tips — tested at 3°C. $51 less than Gore.',
    isArticle: true,
    body: [
      'Cold-weather cycling gloves are one of the categories where branded price tags are hardest to justify. Gore, Castelli and Rapha charge $50–80 for windproof fleece-lined gloves. This pick has been personally tested at 3°C — hands stayed warm on a 90-minute commute with a 30km/h headwind. The fleece interior is genuinely thick and the windproof outer layer does its job.',
      'Touchscreen fingertips mean you can use your phone and Garmin without removing the gloves — more useful than it sounds on a cold training ride when you need to change navigation. Sizing is standard; the wrist cinch keeps them from riding up. At $9, these are the first thing I\'d recommend to any rider heading into autumn.',
    ],
    verdict: '$51 less than Gore Infinium winter gloves. Tested at 3°C — hands stayed warm. One of the biggest value-for-money wins on the site.',
    quote: 'Tested these at 3°C in a headwind. Hands warm the whole way. I sold my Gore gloves after this.',
  },
  {
    id: 'summer-gloves',
    img: 'images/summer-gloves.jpg',
    name: 'Summer Cycling Gloves',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 35,
    price: 6,
    save: 29,
    stars: 4.8,
    reviews: 660,
    link: 'https://temu.to/k/ebf1r80mgkf',
    tagline: 'Race-day minimal gloves — same look and feel as Giro or Specialized for $6.',
    isArticle: true,
    body: [
      'Summer cycling gloves are even more of a commodity than the winter version. The job description is simple: light palm padding, some grip, minimum weight and bulk. These nail it. The back is mesh for ventilation, the palm is a single layer of lightly padded synthetic, and the whole glove weighs almost nothing on your hand.',
      'Buyers compare them directly to Giro Strade Dure and Specialized BG Sport gloves — both in the $30–40 range. At $6 these are in the buy-multiples territory: different colours for different kits, one pair always in the wash, one always on the bike. The most-reviewed glove on the site at 660 reviews, sitting at 4.8 stars.',
    ],
    verdict: 'Same minimal summer glove as Giro or Specialized at $29 less. Buy two pairs in different colours for the price of one branded pair.',
    quote: 'These are just cycling gloves. Light, padded where they need to be, grippy. The Giro ones cost five times more and feel the same.',
  },
  {
    id: 'balaclava',
    img: 'images/balaclava.jpg',
    name: 'Cycling Balaclava',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 40,
    price: 10,
    save: 30,
    stars: 4.8,
    reviews: 122,
    link: 'https://temu.to/k/eltjvwctovt',
    tagline: 'Full head, face, and neck coverage for cold morning rides — $30 less than Castelli.',
    isArticle: true,
    body: [
      'On a sub-5°C morning ride, a balaclava is the difference between suffering and actually enjoying it. This one covers head, face, and neck — the full coverage that a regular cap or ear warmer doesn\'t provide. The fabric is thermal and moisture-wicking; it doesn\'t feel wet and clammy after an hour the way cheap fleece does.',
      'Fit under a helmet is the key test: this sits flush without creating pressure points or making the helmet fit feel loose. The mouth opening is positioned right and the nose cut-out doesn\'t fog glasses. Castelli\'s Estremo balaclava costs $40. This does the same job for $10. One of the most impactful cold-weather kit buys on the site.',
    ],
    verdict: '$30 less than Castelli for full head and face coverage that actually works below 5°C. Don\'t suffer through cold morning rides for want of a $10 balaclava.',
    quote: 'First time using this was at 2°C. I\'d been putting off buying a balaclava because of the price. Should have bought this months ago.',
  },
  {
    id: 'bar-tape',
    img: 'images/bar-tape.jpg',
    name: 'Handlebar Tape',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 30,
    price: 8,
    save: 22,
    stars: 4.9,
    reviews: 465,
    link: 'https://temu.to/k/egw7b3p3pxq',
    tagline: 'Wraps like Fizik or Lizard Skins. One rider has bought it nine times.',
    isArticle: true,
    body: [
      'Handlebar tape wears out. It gets dirty, it compresses, it splits at the edges. Paying $30 every time you re-wrap your bars — which serious cyclists do every 6–12 months — adds up fast. This tape wraps with the same 2.5mm EVA cushioning as Fizik Vento Microtex and Lizard Skins DSP, and at $8 it\'s a quarter of the price.',
      'The buyer who has purchased this nine times is the most compelling review on the site. That\'s not a one-off lucky purchase — it\'s consistent quality over an extended period. The tape is easy to stretch and conform around the bends, the self-adhesive backing stays put, and the end plugs are included. Available in multiple colors that stay vibrant over time.',
    ],
    verdict: '$22 less than Fizik or Lizard Skins. Bought nine times by one rider. The data on this one is unusually strong.',
    quote: 'Nine times. I\'ve re-wrapped my bars nine times with this tape. At $8 a roll, that\'s what one roll of Fizik costs. Do the maths.',
  },
  {
    id: 'mini-pump-cx',
    img: 'images/mini-pump-cx.jpg',
    name: 'Mini Frame Pump',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 45,
    price: 16,
    save: 29,
    stars: 4.8,
    reviews: 166,
    link: 'https://temu.to/k/esgmzz4hf0c',
    tagline: 'Aluminium alloy to 130 PSI, Presta and Schrader — same as Lezyne for $29 less.',
    isArticle: true,
    body: [
      'A mini pump is a piece of kit where quality genuinely matters — a pump that can\'t reach road tyre pressures leaves you either riding on a half-flat or calling for a lift. This aluminium alloy pump hits 130 PSI, which is enough for any road or gravel tyre. Dual-head valve compatibility (Presta and Schrader) means it works with any tube on any bike.',
      'The frame mount bracket is included and holds securely on the downtube or seatstay. Lezyne\'s Road Drive pump hits the same spec and costs $45. At $16, this is the pick for riders who want proper road pump performance without spending Lezyne money. 166 reviews at 4.8 stars is a small but very positive sample.',
    ],
    verdict: '$29 less than Lezyne Road Drive. Same 130 PSI ceiling, same dual valve head. The mini pump for riders who actually inflate tyres properly.',
    quote: 'Pumped a 25c tyre to 100 PSI roadside. No drama. The Lezyne it replaced cost three times more and didn\'t perform any better.',
  },
  {
    id: 'mini-pump-enlee',
    img: 'images/mini-pump-enlee.jpg',
    name: 'Ultracompact Mini Pump',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 45,
    price: 14,
    save: 31,
    stars: 4.8,
    reviews: 202,
    link: 'https://temu.to/k/eziomgb8exg',
    tagline: 'Pen-sized — fits inside the saddle bag underneath the spare tube. Zero extra space.',
    isArticle: true,
    body: [
      'The problem with most mini pumps is that they\'re still pretty big — they need a frame mount or they stick out of a jersey pocket. This one is genuinely pen-sized. It slides inside the saddle bag alongside the tube and levers, taking up almost no additional space. If minimalism is your thing on the bike, this is the pump.',
      'The trade-off with size is effort — you\'ll pump more strokes to reach pressure vs a larger frame pump. But it gets to riding pressure, which is the job. At $14 it\'s $31 less than the Lezyne equivalent. If you ride with a single small saddle bag and hate anything attached to your frame, this is the pick.',
    ],
    verdict: 'The smallest functional pump on the site. $31 less than Lezyne. Fits in the saddle bag so the frame stays clean.',
    quote: 'This thing is genuinely the size of a pen. I keep it inside my saddle bag — I don\'t even have a mount on the bike.',
  },
  {
    id: 'mini-pump-west',
    img: 'images/mini-pump-west.jpg',
    name: 'Mini Pump (Budget Pick)',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 30,
    price: 9,
    save: 21,
    stars: 4.8,
    reviews: 381,
    link: 'https://temu.to/k/el8omjqk5d5',
    tagline: 'Pumped a full 29" MTB tube from flat in 3–4 minutes. Includes all valve adapters.',
    isArticle: true,
    body: [
      'This is the budget pump pick — no aluminium body, no premium branding, just a pump that actually inflates tubes. The standout buyer test: a 29" MTB tube from flat in 3–4 minutes, which is about as demanding as a roadside flat gets. It comes with a complete set of valve adapters, so it works on Presta, Schrader, and Dunlop without carrying anything extra.',
      'At $9, this is the pump you throw in a backpack, keep in the car boot, or hand to a friend who asks for a pump recommendation. Not the premium daily-carry choice (that\'s the aluminium picks above), but completely functional at less than half the price of the next tier up.',
    ],
    verdict: 'The $9 pump that works. Inflates 29" MTB tubes and comes with every valve adapter. The backpack or car-boot pump.',
    quote: 'Pumped a full MTB tube roadside in about 4 minutes. For $9 I keep one in every bag.',
  },
  {
    id: 'repair-kit',
    img: 'images/repair-kit.jpg',
    name: 'Complete Repair Kit',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 70,
    price: 21,
    save: 49,
    stars: 4.8,
    reviews: 566,
    link: 'https://temu.to/k/ebmlb008d88',
    tagline: '17-in-1 tool, tyre levers, and mini pump in a saddle bag — the one-purchase flat kit.',
    isArticle: true,
    body: [
      'This is the kit for the rider who doesn\'t want to think about what they need. It includes a 17-in-1 multi-tool, two tyre levers, a mini pump, and a saddle bag to hold all of it. Every component you need to fix a flat or adjust the bike on the road, packaged together for $21. Buying each piece separately — even at budget prices — would cost more.',
      'The convenience factor is the real story: this makes an ideal gift for a rider who doesn\'t have their flat kit sorted, or the perfect setup for a commuter bike. 566 reviews at 4.8 stars shows this isn\'t a novelty — it works. The saddle bag included is a proper one, not a thin ziplock. At $49 less than buying an equivalent branded bundle, this is a clear win.',
    ],
    verdict: '$49 less than buying an equivalent branded bundle. The complete one-purchase flat kit. Great for commuters and gift-givers.',
    quote: 'Bought this for my partner\'s bike. Complete kit, decent quality, zero thought required. Does the job for $21.',
  },
  {
    id: 'gps-mount',
    img: 'images/gps-mount.jpg',
    name: 'GPS Computer Mount',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 50,
    price: 6,
    save: 44,
    stars: 4.8,
    reviews: 825,
    link: 'https://temu.to/k/eiqc42xlow8',
    tagline: 'Holds solid over cobbles and rough road. $44 less than the official Garmin out-front mount.',
    isArticle: true,
    body: [
      'Garmin charges $50 for an out-front mount. It\'s a small piece of plastic and aluminium that holds a computer in front of your stem. The function is simple and the margin is enormous. This mount holds a Garmin Edge (any model with the standard quarter-turn mount) solid over cobbles, rough chip-seal, and fast descents. It has not moved or vibrated loose on any ride it\'s been tested on.',
      'Over 800 reviews at 4.8 stars is about as thorough a test as a non-structural bike accessory can get. Multiple buyers specifically mention using it for months with no movement. The out-front position puts the computer in your natural line of sight without having to look down past the stem — exactly what you get from the branded version, for $44 less.',
    ],
    verdict: '$44 less than official Garmin mount. Holds through cobbles and rough road. One of the highest-reviewed picks on the site.',
    quote: 'Same quarter-turn mount, same out-front position, $44 cheaper. I don\'t understand why anyone buys the official Garmin mount.',
  },
  {
    id: 'stem-mount',
    img: 'images/stem-mount.jpg',
    name: 'Stem Computer Mount',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 45,
    price: 10,
    save: 35,
    stars: 4.8,
    reviews: 113,
    link: 'https://temu.to/k/ebxqyggsmvz',
    tagline: 'Aluminium + carbon GPS stem mount — looks like a €40 K-Edge, costs $10.',
    isArticle: true,
    body: [
      'K-Edge makes beautiful aluminium GPS mounts for €40+. This one uses the same materials — aluminium body with carbon-weave detailing — and does the same job for $10. The stem clamp is solid, works on 28.6mm to 35mm stems, and the quarter-turn GPS receiver is compatible with Garmin, Wahoo, and any other standard-mount computer.',
      'Stem mounts have an aesthetic advantage over out-front mounts on some bike setups — they keep the front end cleaner and the computer closer to the centre line. If that\'s your preference, this is the budget way to get there. 113 reviews is a smaller sample, but 4.8 stars is consistent with the quality level.',
    ],
    verdict: 'Looks like a €40 K-Edge stem mount. Works like one. Costs $10. For riders who prefer a clean stem-mount setup.',
    quote: 'Carbon-look aluminium stem mount for $10. Three people have asked where I got it expecting to pay three times more.',
  },
  {
    id: 'cleaning-kit',
    img: 'images/cleaning-kit.jpg',
    name: 'Bike Cleaning Kit (8-piece)',
    cat: 'Tools',
    filters: ['tools', 'bigsave'],
    branded: 50,
    price: 16,
    save: 34,
    stars: 4.9,
    reviews: 221,
    link: 'https://temu.to/k/em2qbrjkbyt',
    tagline: '8-piece brush set for chain, cassette, and frame — directly compared to Muc-Off by buyers.',
    isArticle: true,
    body: [
      'The Muc-Off 8-piece brush kit costs $50 and is the benchmark in bike cleaning. Multiple buyers of this kit compare it directly to Muc-Off and find the brush quality essentially equivalent — the bristle density, handle ergonomics, and brush sizes that matter (chain scrubber brush, cassette brush, frame brush, detail brush) are all there.',
      '4.9 stars from 221 reviews is the highest product rating on the site alongside the saddle bag. At $16 this is a $34 saving for a kit that covers every part of the drivetrain and frame. Clean bikes last longer and are easier to work on — this is one of the picks where the saving compounds over time through better drivetrain longevity.',
    ],
    verdict: '$34 less than Muc-Off with the same brush coverage. Buyers compare it directly to branded kits. One of the highest-rated picks on the site.',
    quote: 'Side by side with my Muc-Off kit, I cannot tell the bristles apart. This costs a third of the price.',
  },
  {
    id: 'running-caps',
    img: 'images/running-caps.jpg',
    name: 'Running Caps (2-pack)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 60,
    price: 8,
    save: 52,
    stars: 4.8,
    reviews: 514,
    link: 'https://temu.to/k/eo6u0nmxqb2',
    tagline: 'Two mesh running caps for $8 — vs $30 each for Nike or Salomon equivalents.',
    isArticle: true,
    body: [
      'Nike AeroBill and Salomon running caps cost $28–32 each. This pack gives you two caps for $8 — four times less for twice as many. The mesh panels are proper ventilation mesh, the brim is structured enough to stay flat in wind, and the adjustable back closure fits all head sizes.',
      'For hot-weather running, trail racing, or triathlon where you want a cap but don\'t want to cook, this is the play. Keep one in the kit bag, one at home. Two different colors means you can match your kit. 514 reviews at 4.8 stars is strong validation for something this simple.',
    ],
    verdict: 'Two caps for $8, saving $52 vs buying two Nike equivalents. The running cap is a wear-and-replace item — don\'t pay $30 each for them.',
    quote: 'Two mesh running caps for $8. I wear them on trails, in races, training in the sun. Nike charges $30 for one.',
  },
  {
    id: 'calf-sleeves',
    img: 'images/calf-sleeves.jpg',
    name: 'Compression Calf Sleeves',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 50,
    price: 6,
    save: 44,
    stars: 4.8,
    reviews: 4829,
    link: 'https://temu.to/k/ev6b8htdopf',
    tagline: 'Reduces travel swelling and speeds recovery — 72,000+ sold. $44 less than Compressport.',
    isArticle: true,
    body: [
      'Compressport R2 calf sleeves cost $50. They work by applying graduated compression to the lower leg — tighter at the ankle, less so at the calf — which reduces muscle oscillation during running and aids venous return during recovery. This pick does exactly the same thing for $6. Over 72,000 units sold across the product category gives a very large evidence base.',
      'Nearly 5,000 reviews at 4.8 stars makes this one of the most validated picks on the site. Buyers use them for long-haul flights to prevent DVT, during ultramarathons for calf fatigue reduction, and post-race for recovery. The graduated compression is genuine, not just tight fabric — you feel the compression differential from ankle to calf. $44 less than Compressport for the same function.',
    ],
    verdict: '$44 less than Compressport R2. Nearly 5,000 reviews at 4.8 stars. Genuine graduated compression for running and recovery.',
    quote: 'Wore these on a 15-hour flight and a 50km ultra the following weekend. Legs recovered faster than without. Compressport cost me $50. These cost $6.',
  },
  {
    id: 'running-belt',
    img: 'images/running-belt.jpg',
    name: 'Running Belt',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 35,
    price: 8,
    save: 27,
    stars: 4.8,
    reviews: 948,
    link: 'https://temu.to/k/eoq9u2nze0b',
    tagline: 'Zero-bounce belt for phone, keys, and card — 1M+ sold. $27 less than Nathan or Flipbelt.',
    isArticle: true,
    body: [
      'Flipbelt charges $35 for a running waist belt. Nathan charges similar. Both are just a strip of stretchy fabric with pockets. This one does the same thing at $8 — holds your phone flat against your lower abdomen with zero bounce, plus a key clip and card pocket. The 1 million+ units sold figure makes this one of the most purchased running accessories on the platform.',
      'Zero bounce is the feature that matters. Any running belt that bounces becomes annoying within 15 minutes. Multiple buyers with large phones confirm that a 6.7" device sits flush and doesn\'t move during tempo runs and races. Adjustable sizing covers a wide waist range. $27 saved for something you\'ll use on every run without carrying.',
    ],
    verdict: '$27 less than Flipbelt or Nathan. 1M+ sold. Zero bounce confirmed by runners with large phones. The running belt that does its job.',
    quote: 'My Flipbelt fell apart at the seams after a year and cost $35. This has lasted longer, cost $8, and doesn\'t bounce any more than the branded version.',
  },
  {
    id: 'elastic-laces',
    img: 'images/elastic-laces.jpg',
    name: 'Elastic No-Tie Laces',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 12,
    price: 1.7,
    save: 10,
    stars: 4.8,
    reviews: 9201,
    link: 'https://temu.to/k/eexx1xt6su3',
    tagline: 'Shoes on in 3 seconds in T2 — same as $12 Lock Laces for $1.70.',
    isArticle: true,
    body: [
      'Lock Laces are the standard elastic no-tie lace for triathlon and quick-run shoes. They cost $12 and work brilliantly. These cost $1.70 and work identically — elastic cord, lace cord holder, and a clip. Shoes on in three seconds, snug and secure, no knot to undo. For triathlon T2, this saves 20–30 seconds in transition and around $10 per pair of shoes.',
      'Over 9,200 reviews at 4.8 stars makes this the most-reviewed product on the site by a large margin. Multiple triathletes, OCR runners, and everyday runners confirm they stay put for full race distances. The cheapest pick on the site at $1.70 — which means it\'s also the highest percentage saving: $10.30 on a $12 item.',
    ],
    verdict: 'The cheapest pick on the site. Same as $12 Lock Laces for $1.70. Over 9,200 reviews. For triathlon transitions alone this pays for itself in seconds saved.',
    quote: 'I have these in every pair of running shoes I own. $1.70 each. Lock Laces are $12. I genuinely cannot find a reason to pay more.',
  },
  {
    id: 'foam-roller',
    img: 'images/foam-roller.jpg',
    name: 'Foam Roller Set (5-piece)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 70,
    price: 14,
    save: 56,
    stars: 4.8,
    reviews: 370,
    link: 'https://temu.to/k/e56n3u6bii7',
    tagline: '5-piece recovery kit — "not worse than Blackroll" per one buyer. $56 less than branded.',
    isArticle: true,
    body: [
      'Blackroll and TriggerPoint charge $50–70 for foam rollers that compress foam over time and last a couple of years with heavy use. This 5-piece set covers the same range of recovery tools — full cylinder, half roller, ball, massage stick — for $14 total. One buyer states directly: "not worse than Blackroll after six months of use." That\'s the honest benchmark comparison.',
      'For athletes who are just starting to incorporate foam rolling and don\'t know which tools they\'ll use, a 5-piece set at $14 is a no-risk way to find out. For experienced rollers, the savings are straightforward: $56 kept in pocket. The set covers IT band, quads, calves, thoracic spine, and piriformis — every major running-relevant tissue.',
    ],
    verdict: '$56 less than a comparable Blackroll set. Five pieces covering every major muscle group. The recovery kit for athletes who don\'t want to overpay for foam.',
    quote: 'Six months in and this set performs identically to my Blackroll roller that cost four times as much.',
  },
  {
    id: 'resistance-bands',
    img: 'images/resistance-bands.jpg',
    name: 'Resistance Bands Set',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 55,
    price: 13,
    save: 42,
    stars: 4.8,
    reviews: 278,
    link: 'https://temu.to/k/eosiemk6lob',
    tagline: 'Up to 6 TPE resistance bands — full strength kit for $42 less than Rogue or Perform Better.',
    isArticle: true,
    body: [
      'Resistance bands are used for warm-up, mobility work, and strength exercises — hip abductors, glutes, shoulder stability. Rogue and Perform Better charge $55+ for a set. This pack of up to six TPE (thermoplastic elastomer) bands covers the same resistance range: light bands for warm-up and activation, heavier bands for loaded exercises.',
      'TPE is the correct material for resistance bands — it has better temperature resistance and longevity than latex, especially for athletes who leave kit in hot cars. 278 reviews at 4.8 stars. The six-band set gives you a complete resistance range from warm-up to serious strength work. At $13, this is a $42 saving for a complete kit.',
    ],
    verdict: '$42 less than a Rogue band set for the same six-resistance TPE range. The complete strength and mobility kit for serious endurance athletes.',
    quote: 'Use these every day for hip activation before running. TPE material, good resistance range. Rogue charges $55 for a worse set.',
  },
  {
    id: 'mini-bands',
    img: 'images/mini-bands.jpg',
    name: 'Mini Resistance Bands (3-pack)',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 30,
    price: 7,
    save: 23,
    stars: 4.8,
    reviews: 720,
    link: 'https://temu.to/k/equ2h6wy1ac',
    tagline: 'Three mini bands for hip activation and injury prevention. $23 less than physio brands.',
    isArticle: true,
    body: [
      'Mini loop bands are a physio staple for hip and glute activation, IT band injury prevention, and runner-specific strength work. The physiotherapy versions from TheraBand and similar brands cost $8–12 each. This 3-pack covers light, medium, and heavy resistance for $7 total — one set that handles everything from warm-up to loaded exercises.',
      '720 reviews at 4.8 stars. These are used by runners, cyclists, and triathletes for activation work, rehab, and strength training. The key thing that breaks mini bands is the material snapping at the edges — these are consistently reported to last through sustained daily use. At $7 for three, there\'s almost no reason to buy the branded version.',
    ],
    verdict: '$23 less than three TheraBand mini loops. Covers light, medium, and heavy resistance. The standard hip activation kit for endurance athletes.',
    quote: 'I go through mini bands — they snap eventually. At $7 for three I don\'t care. The physio brand set cost $30 and lasted the same time.',
  },
  {
    id: 'race-belt',
    img: 'images/race-belt.jpg',
    name: 'Triathlon Race Belt',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 18,
    price: 3,
    save: 15,
    stars: 4.8,
    reviews: 1054,
    link: 'https://temu.to/k/e3nurz30cdv',
    tagline: 'Race belt with gel loops — T2 ready in 2 seconds. Holds 6 gels. $3 vs $18 branded.',
    isArticle: true,
    body: [
      'A triathlon race belt is one of the most overpriced items in the sport. It\'s an elastic band with a clip and some loops. Orca and Nathan charge $15–18 for it. This one costs $3, clips on in T2 in about two seconds, and holds up to six gels on the gel loops — enough fuel for a half-Ironman run leg without needing pockets.',
      'Over 1,000 reviews at 4.8 stars. The clip is the key component — it needs to be quick to attach in transition and secure enough not to pop open during a run. Multiple buyers confirm both. The race number sits flush with the elastic and doesn\'t flap, which is the practical thing that matters in a race.',
    ],
    verdict: '$15 less than Orca or Nathan race belts for something that is literally a clip and some elastic. Holds 6 gels. Over 1,000 people use it in races.',
    quote: 'Clipped on in 2 seconds in T2, held my race number flat the whole marathon. Orca charges $18 for the same thing.',
  },
  {
    id: 'swim-cap',
    img: 'images/swim-cap.jpg',
    name: 'Silicone Swim Cap',
    cat: 'Running',
    filters: ['running', 'under5'],
    branded: 15,
    price: 2.5,
    save: 13,
    stars: 4.8,
    reviews: 984,
    link: 'https://temu.to/k/et2k74knz7l',
    tagline: 'Silicone twice as thick as branded equivalents per one buyer — at $2.50, just buy five.',
    isArticle: true,
    body: [
      'Silicone swim caps are a staple for triathlon open-water swimming and pool training. TYR and Arena charge $12–15 for theirs. This one is $2.50 and one buyer specifically notes it\'s thicker silicone than the branded cap they replaced. Thicker silicone means better insulation in cold open water and a longer lifespan before splitting.',
      'Nearly 1,000 reviews at 4.8 stars. The pitch here is simple: buy five. Even at $2.50 each, five caps cost $12.50 — less than one TYR cap. Keep one in the pool bag, one in the race kit, one as a backup. At this price, cap degradation stops being something you think about.',
    ],
    verdict: '$13 less than TYR. Reportedly thicker silicone than branded equivalents. Buy five for the price of one Arena cap — and never think about swim caps again.',
    quote: 'Thicker silicone than my $15 TYR cap. At $2.50 I bought eight of them. Enough caps for the next two years for the price of one branded pair.',
  },

  // ── ALIEXPRESS PICKS ─────────────────────────────────────────────────

  {
    id: 'cycling-jersey-ss',
    name: 'Cycling Jersey',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 90,
    price: 10.94,
    save: 79,
    stars: 4.8,
    reviews: 3247,
    link: 'https://s.click.aliexpress.com/e/_EHc1YVg',
    tagline: 'Same race-day look as a $90 Castelli jersey. Costs $11.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Castelli and Rapha charge $90–130 for race jerseys. The premium is mostly branding — the underlying technical fabric (polyester-spandex blend, sublimated print, three rear pockets, full zipper) is producible at a fraction of the cost. This jersey uses that same construction at $11. With over 3,200 reviews at 4.8 stars, it\'s one of the most validated clothing picks on the site.',
      'Fit is the key thing with any cycling jersey. This one runs slim — order up one size from your usual if you\'re between sizes. The rear pockets are full-size and hold two gels and a phone each. The sublimated print doesn\'t fade with normal washing. On the bike, the aerodynamic profile of a well-fitted jersey is the same regardless of the badge — and at $11 you can afford to get the sizing right.',
    ],
    verdict: '$79 less than Castelli for a race jersey that looks and functions identically on the bike. 3,000+ reviews confirm the quality.',
    quote: 'Wore this to a local crit and had two people ask what team I was on. It\'s a $11 jersey from AliExpress. Nobody can tell.',
  },
  {
    id: 'overshoes',
    name: 'Cycling Overshoes',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 60,
    price: 13.85,
    save: 46,
    stars: 4.7,
    reviews: 1584,
    link: 'https://s.click.aliexpress.com/e/_EvQd24W',
    tagline: 'Waterproof neoprene shoe covers — stays dry for $14 vs $60 branded.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Cycling overshoes have one job: keep your feet dry and warm when it\'s cold and wet. Specialized and Castelli neoprene shoe covers cost $50–60. This pick uses the same 3mm neoprene construction at $14. The toe cap is reinforced for cleat clearance, the zip runs up the back of the heel (the correct closure position for road cycling), and the silicone grip on the sole stops you sliding in the wet.',
      'Sizing is crucial for overshoes — go up half a size from your cycling shoe size for a snug fit over the shoe. 1,584 reviews at 4.7 stars reflects the real-world testing: these get used in wet autumn and winter rides and hold up. The neoprene is genuinely waterproof in normal rain, though full submersion would defeat it as it would any shoe cover.',
    ],
    verdict: '$46 less than Specialized overshoes. Same neoprene construction, same cleat cut, same heel zip. The wet-weather essential that doesn\'t need a premium price.',
    quote: 'Three hours in the rain and my feet stayed dry. These are $14. My last pair of Castelli overshoes cost $60 and worked the same way.',
  },
  {
    id: 'hydration-vest',
    name: 'Running Hydration Vest',
    cat: 'Running',
    filters: ['running', 'bigsave'],
    branded: 100,
    price: 6.05,
    save: 94,
    stars: 4.8,
    reviews: 5921,
    link: 'https://s.click.aliexpress.com/e/_ExFvLp8',
    tagline: 'Feels like a Salomon vest. Costs $94 less.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Salomon Active Skin 8 costs $100 and is the benchmark trail running hydration vest. The key features — front flasks in chest pockets, adjustable shoulder straps, back storage, bounce reduction — are what you\'re paying for. This vest delivers all of them at $6. The front pockets hold two 500ml flasks, the shoulder straps are elastic and adjustable, and the back has enough storage for a jacket and gels.',
      'Nearly 6,000 reviews at 4.8 stars makes this one of the most reviewed picks on the site. Multiple trail runners and ultra runners report using this for race distances up to 50km. The bounce reduction on the chest pockets is the key test — loose flasks in chest pockets ruin a run. This holds them tight. At $6 vs $100, the value case is overwhelming.',
    ],
    verdict: 'The biggest savings on the site at $94. Nearly 6,000 reviews at 4.8 stars from real trail runners. Works for races up to 50km.',
    quote: 'Ran a 50km trail race in this vest. Zero bounce, front flasks stayed put, enough storage. My Salomon cost $100 and isn\'t meaningfully better.',
  },
  {
    id: 'bib-shorts',
    name: 'Bib Shorts',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 140,
    price: 24.41,
    save: 116,
    stars: 4.9,
    reviews: 4813,
    link: 'https://s.click.aliexpress.com/e/_EQd5V0a',
    tagline: '6-hour padded bibs — Castelli-level comfort for $116 less.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Bib shorts are where the branded markup is most extreme — Castelli Progetto X2 bibs cost $140–200 and the main thing you\'re paying for is the pad (chamois). This pick uses a genuine high-density foam chamois with a multi-panel cut, and buyers report genuine comfort through 5–6 hour rides. The silicone leg grippers hold without leaving marks.',
      '4.9 stars from 4,813 reviews is the joint-highest rating on the site — and that sample size is enormous for a cycling garment. The key caveat: fit is personal, and bib shorts are closer to fit-dependent than most cycling gear. Read the sizing chart carefully and note that Chinese sizing runs one size smaller than European. If in doubt, size up. But at $24 vs $140, the risk of getting the size slightly wrong is completely manageable.',
    ],
    verdict: '$116 less than Castelli bibs. 4.9 stars from nearly 5,000 reviewers. Comfortable through 6 hours. Size up and read the chart carefully.',
    quote: 'Six-hour Étape ride in these. Pad held up, no chafing, legs weren\'t marked by the grippers. My Castelli bibs are currently sitting unused.',
  },
  {
    id: 'cycling-sunglasses',
    name: 'Cycling Sunglasses',
    cat: 'Cycling',
    filters: ['cycling', 'under5', 'bigsave'],
    branded: 180,
    price: 4.30,
    save: 176,
    stars: 4.7,
    reviews: 2436,
    link: 'https://s.click.aliexpress.com/e/_EJyXqp0',
    tagline: 'UV400 lenses, aero frame. Looks like Oakley. Costs $4.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Oakley Jawbreaker sunglasses cost $180+ and are the most-copied cycling sunglass design on the market. This is one of those copies — aero wrap frame, large lens coverage, UV400 protection. The UV400 rating is the important number: it means the lenses block 99–100% of UV-A and UV-B radiation, which is the actual protection function. You don\'t need $180 lenses for that.',
      'The largest savings on the site in absolute percentage terms — $176 saved on a $4.30 purchase. The trade-off vs genuine Oakley: optical clarity is slightly lower, and these won\'t survive a crash the way a $180 polycarbonate lens does. But for training rides and everyday use where you\'re not expecting to face-plant at 40km/h, these do the visual job. 2,436 reviews at 4.7 stars confirms the use case.',
    ],
    verdict: 'Biggest percentage saving on the site — $176 for $4.30. UV400 lenses, aero frame. Not for high-speed crash scenarios, but for training and everyday riding: completely functional.',
    quote: 'UV400 protection is UV400 protection. These do what sunglasses are supposed to do and cost $4. I\'ve stopped buying the branded ones.',
  },
  {
    id: 'jersey-ls',
    name: 'Long Sleeve Jersey',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 110,
    price: 25.30,
    save: 85,
    stars: 4.8,
    reviews: 3092,
    link: 'https://s.click.aliexpress.com/e/_EIH3daI',
    tagline: 'SPF50+ race jersey — premium fit and feel for $85 less.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Long sleeve cycling jerseys serve two seasons: cool spring/autumn rides where a short sleeve jersey isn\'t quite enough, and hot summer rides where SPF50+ coverage prevents sunburn on exposed arms. This jersey covers both — lightweight long sleeves with UPF50+ protection and the same three-pocket, full-zip construction as an $110 race jersey.',
      'Over 3,000 reviews at 4.8 stars. The fit is the standout detail: multiple buyers describe it as genuinely race-fit, not the boxy cut of cheaper cycling garments. That means it stays aerodynamic on the bike and doesn\'t flap at speed. At $25 vs $110, you could buy four of these for the price of the Rapha equivalent.',
    ],
    verdict: '$85 less than a Rapha long sleeve jersey. SPF50+ protection, race fit confirmed by 3,000+ buyers. The spring and summer long-sleeve choice.',
    quote: 'Race-fit long sleeve for $25. I own three in different colors for the price of one Rapha equivalent. The fit is genuinely premium.',
  },
  {
    id: 'cycling-gilet',
    name: 'Cycling Wind Gilet',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 100,
    price: 12.55,
    save: 87,
    stars: 4.8,
    reviews: 1927,
    link: 'https://s.click.aliexpress.com/e/_EwvKNfY',
    tagline: 'Windproof jersey-pocket gilet — $87 cheaper than Castelli Perfetto.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'The Castelli Perfetto Light Wind Vest costs $100 and is the benchmark for packable windproof gilets. The design is simple: windproof front panel, mesh back for ventilation, packs into a rear jersey pocket. This pick does exactly that for $13. The windproof fabric is proper windblock material — buyers specifically test it into headwinds and confirm it does the job.',
      'The packability is what makes a gilet different from a jacket — you take it off when the weather improves and it disappears into a jersey pocket. This packs down small enough to fit in a standard pocket. 1,927 reviews at 4.8 stars. At $87 less than Castelli, this is the pick for any cyclist who regularly rides in variable conditions and needs a reliable wind layer.',
    ],
    verdict: '$87 less than Castelli Perfetto. Packs into a jersey pocket, blocks wind properly. One of the highest-value kit picks on the site.',
    quote: 'Tested this into a 40km/h headwind at 8°C. Wind didn\'t get through. Castelli charges $100 for the same thing. This was $13.',
  },
  {
    id: 'tt-handlebar',
    name: 'Carbon TT Handlebar',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 250,
    price: 36.91,
    save: 213,
    stars: 4.7,
    reviews: 1183,
    link: 'https://s.click.aliexpress.com/e/_Ewg1SX8',
    tagline: '3K matte carbon TT bars — same aero position as Zipp for $213 less.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Zipp Vuka Clip TT bars cost $250. They are carbon fibre and they allow you to adopt an aero time trial position on a road or triathlon bike. This pick is also carbon fibre — 3K weave matte finish — and allows the same aero position for $37. The weight saving vs aluminium TT bars is real, and the aerodynamic position you can achieve is identical to the Zipp.',
      'Important caveat: this is a structural component. 1,183 reviews at 4.7 stars gives reasonable confidence, but with any unbranded carbon cockpit component, inspection before each ride is sensible. Check for cracks at the clamp and at the bend. For triathlon and time trial training where crashes are rare, this is a legitimate budget option. For criterium racing or aggressive riding where a bar failure would be catastrophic, stick with a reputable brand.',
    ],
    verdict: '$213 less than Zipp TT bars. Real 3K carbon, same aero position. Inspect before each ride as with any structural component.',
    quote: 'Same aero position as my Zipp bars. I use these on my training tri bike — identical position, works perfectly, $213 cheaper.',
  },
  {
    id: '3d-saddle',
    name: '3D Printed Bike Saddle',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 400,
    price: 43.02,
    save: 357,
    stars: 4.9,
    reviews: 2674,
    link: 'https://s.click.aliexpress.com/e/_ExdfFQI',
    tagline: '3D-printed ultralight saddle — same tech as $400 Specialized Power Mirror.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Specialized Power Mirror and Fizik Adaptive saddles use 3D-printed lattice foam construction — a lightweight, breathable material that conforms to sit bone pressure better than traditional foam. These saddles retail for $350–450. This pick uses the same 3D-print lattice construction for $43. The technology is genuinely the same: additive-manufactured elastomeric lattice over a carbon-look base.',
      '4.9 stars from 2,674 reviews — the highest-rated AliExpress pick on the site by a large margin. Multiple buyers specifically compare it to the Specialized Power Mirror and report equivalent comfort. The saddle cutout relieves perineal pressure for long rides. At $357 less than the Specialized, this has the biggest absolute saving on the site. Like TT bars, inspect this periodically as it is a structural component.',
    ],
    verdict: 'Biggest absolute saving on the site at $357. 4.9 stars from 2,674 buyers comparing it to Specialized Power Mirror. The 3D-print technology that used to cost $400.',
    quote: 'I put this next to my Specialized Power Mirror and cannot find a meaningful difference in feel. This cost $43. The Specialized cost $400.',
  },
  {
    id: 'aero-bars',
    name: 'Clip-On Aero Bars',
    cat: 'Cycling',
    filters: ['cycling', 'bigsave'],
    branded: 90,
    price: 14.82,
    save: 75,
    stars: 4.8,
    reviews: 6341,
    link: 'https://s.click.aliexpress.com/e/_EGHCLAO',
    tagline: 'Adds a full TT position to any road bike for $14.',
    isArticle: true,
    source: 'aliexpress',
    body: [
      'Clip-on aero bars are the most cost-effective aero upgrade available to a road or triathlon cyclist. You clamp them onto your existing drop bars and gain a full time trial position — arms forward, torso low, drag dramatically reduced. Profile Design and Syntace clip-ons cost $90+. These do the same thing for $15, with 6,341 reviews to back it up.',
      'The clamping mechanism is the key question for any clip-on bar: does it stay put? At 4.8 stars from over 6,000 buyers — the most-reviewed product on the entire site — the answer is yes. Extension length and arm-rest position are adjustable to fit different shoulder widths. For flat triathlon courses, sportives, or any ride where you spend time at the front, this is a $75 saving for a meaningful aero upgrade.',
    ],
    verdict: 'The most-reviewed pick on the site at 6,341 reviews. Adds a TT position to any road bike for $15 vs $90. A genuine aero upgrade with enormous social proof.',
    quote: 'Spent $15 to add a full TT position to my road bike. More aero gain than any other $15 purchase I\'ve made in cycling.',
  },
];
